### ISSUE TITLE
Editor Anpassung -> Ergebnis Eingabe 

### ISSUE THREAD

**Issue by matthiasharrer** [Gruppe-1-Rezepte/rdlang-group1#5]
Eingabe von Ergebnissen im Editor zur Zeit nicht möglich.

Falls Ergebnis in Freitextfeld (#3) eigene Lösung für Ergebnis Eingabe besteht, nicht benötigt

**Comment by Mopedonaut** [comment]
Tut jetzt mit Alt+Enter.
Wollen wir auch eine intuitivere Art unterstützen, nämlich dass der User einfach das "->" tippt?
